name: json_interop
description: Raw interop for the JSON object
author: Kasper Peulen <kasperpeulen@gmail.com>
homepage: https://github.com/kasperpeulen/JSON_interop.dart
version: 0.0.1+2
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  js: '^0.6.0'
dev_dependencies:
  test: ^0.12.6+1
  grinder: ^0.8.0+1
  browser: ^0.10.0+2
